apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: echo-server
  name: echo-server
spec:
  replicas: 20
  selector:
    matchLabels:
      run: echo-server
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: REDIRECT
        sidecar.istio.io/status: '{"version":"610f2b5742375d30d7f484e296fd022086a4c611b5a6b136bcf0758767fefecc","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
        traffic.sidecar.istio.io/excludeInboundPorts: "15020"
        traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
      creationTimestamp: null
      labels:
        run: echo-server
    spec:
      containers:
        - image: yuyileiyuyilei/grpcserver:v1.1
          imagePullPolicy: Always
          name: echo-server
          resources: {}
        - args:
            - proxy
            - sidecar
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --configPath
            - /etc/istio/proxy
            - --binaryPath
            - /usr/local/bin/envoy
            - --serviceCluster
            - echo-server.default
            - --drainDuration
            - 45s
            - --parentShutdownDuration
            - 1m0s
            - --discoveryAddress
            - istio-pilot.istio-system:15010
            - --zipkinAddress
            - zipkin.istio-system:9411
            - --dnsRefreshRate
            - 300s
            - --connectTimeout
            - 10s
            - --proxyAdminPort
            - "15000"
            - --concurrency
            - "2"
            - --controlPlaneAuthPolicy
            - NONE
            - --statusPort
            - "15020"
            - --applicationPorts
            - ""
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ISTIO_META_POD_PORTS
            value: |-
              [
              ]
          - name: ISTIO_META_CLUSTER_ID
            value: Kubernetes
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ISTIO_META_CONFIG_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SDS_ENABLED
            value: "false"
          - name: ISTIO_META_INTERCEPTION_MODE
            value: REDIRECT
          - name: ISTIO_META_INCLUDE_INBOUND_PORTS
          - name: ISTIO_METAJSON_LABELS
            value: |
              {"run":"echo-server"}
          - name: ISTIO_META_WORKLOAD_NAME
            value: echo-server
          - name: ISTIO_META_OWNER
            value: kubernetes://api/apps/v1/namespaces/default/deployments/echo-server
        image: docker.io/istio/proxyv2:1.3.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
          - containerPort: 15090
            name: http-envoy-prom
            protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15020
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
          - mountPath: /etc/istio/proxy
            name: istio-envoy
          - mountPath: /etc/certs/
            name: istio-certs
            readOnly: true
            initContainers:
              - args:
                  - -p
                  - "15001"
                  - -z
                  - "15006"
                  - -u
                  - "1337"
                  - -m
                  - REDIRECT
                  - -i
                  - '*'
                  - -x
                  - ""
                  - -b
                  - '*'
                  - -d
                  - "15020"
                image: docker.io/istio/proxy_init:1.3.0
                imagePullPolicy: IfNotPresent
                name: istio-init
                resources:
                  limits:
                    cpu: 100m
                    memory: 50Mi
                  requests:
                    cpu: 10m
                    memory: 10Mi
                securityContext:
                  capabilities:
                    add:
                      - NET_ADMIN
                  runAsNonRoot: false
                  runAsUser: 0
              volumes:
                - emptyDir:
                    medium: Memory
                  name: istio-envoy
                - name: istio-certs
                  secret:
                    optional: true
                    secretName: istio.default
            status: {}
            ---
            apiVersion: v1
            kind: Service
            metadata:
              labels:
                run: echo-server
              name: echo-server
            spec:
              ports:
                - name: grpc
                  port: 8080
                  targetPort: 8080
              selector:
                run: echo-server
              sessionAffinity: None
              type: ClusterIP
            ---
